name: My first workflow
on: push
job:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Adding checkout Action
      uses: actions/checkout@v5
    - name: Welcom message
      run: echo "My first GitHub Action job"

    - name: list files
      run: list

    - name: Read files
      run: cat README.md